# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LVC_demo' do
pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git'
end

target 'LVC_demoTests' do

end

